version: "2"
linters: 
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - errcheck
    - forbidigo
    - ginkgolinter
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
  settings:
    forbidigo:
      forbid:
        - pattern: ^(fmt\.Print(|f|ln)|print|println)$
          msg: Do not commit print statements.
        - pattern: errors\.Wrap
          msg: Do not use errors.Wrap use fmt.Errorf()
        - pattern: errors\.Cause
          msg: Don not use errors.Cause use errors.As or errors.Is
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    gci:
      sections:
        - standard
        - default
        - localmodule

# issues:
# output:
run:
  tests: true
  concurrency: 4
severity:
  default: error
