version: '3'

silent: true

vars:
  TOOLS_DIR:
    sh: echo "`pwd`/bin/tools"

  DEV_TOOLS: |
    github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.5

tasks:
  default:
    cmds:
      - task: tidy
      - task: fmt
      - task: lint
      - task: test

  tidy:
    desc: updates and tidies dependencies
    cmds:
      - echo "- Tidy..."
      - go mod tidy

  fmt:
    desc: runs golangci fmt
    cmds:
      - echo "- Format..."
      - '"{{.TOOLS_DIR}}"/golangci-lint fmt -v ./...'

  lint:
    desc: runs golangci lint
    cmds:
      - echo "- Lint..."
      - '"{{.TOOLS_DIR}}"/golangci-lint run -v ./...'

  test:
    desc: runs all tests
    cmds:
      - echo "- Test..."
      - go test --race ./...
      - '"{{.TOOLS_DIR}}"/ginkgo -v ./...'

  dev:
    desc: runs server locally with dev settings
    cmds:
      - echo "- Starting development server..."
      - cmd: test -f config.yaml || cp config.yaml.example config.yaml
        silent: true
      - echo "  Using VERSION_TAG=dev"
      - echo "  Server will be available at http://localhost:8081"
      - echo "  Press Ctrl+C to stop the server"
      - echo "  =========================================="
      - VERSION_TAG=dev go run cmd/life-log/main.go

  dev-check:
    desc: runs checks and then starts development server
    cmds:
      - task: default
      - task: dev

  dev-tools:install:
    desc: installs development tools
    cmds:
      - echo "- Dev Tools Install..."
      - |
        export GOBIN="{{.TOOLS_DIR}}"
        {{range $i, $tool := .DEV_TOOLS | trim | splitLines -}}
          go install {{$tool}}
        {{end}}
      - ls -l "{{.TOOLS_DIR}}"
 
