version: '3'

silent: true

vars:
  TOOLS_DIR:
    sh: echo "`pwd`/bin/tools"

  DEV_TOOLS: |
    github.com/daixiang0/gci@v0.13.6

tasks:
  default:
    cmds:
      - task: tidy

  tidy:
    - echo "- Tidy..."
    - go mod tidy

  dev-tools:install:
    - echo "- Dev Tools Install..."
    - |
      export GOBIN="{{.TOOLS_DIR}}"
      {{range $i, $tool := .DEV_TOOLS | trim | splitLines -}}
        go install {{$tool}}
      {{end}}
    - task: dev-tools:act-install
    - ls -l "{{.TOOLS_DIR}}"
 
  dev-tools:act-install:
    - curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/nektos/act/master/install.sh | bash
    - mv ./bin/act ./bin/tools/act

  act:push:
    - |
      export PATH="${PATH}:{{.TOOLS_DIR}}"
      act push

  act:pull-request:
    - |
      export PATH="${PATH}:{{.TOOLS_DIR}}"
      act pull_request
