services:
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      - NGINX_PORT=80
      - LIFE_LOG_PORT=8080
    depends_on:
      - life-log

  life-log:
    image: ghcr.io/${GHCR_USERNAME}/life-log:${VERSION_TAG}
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    environment:
      # Secrets
      - VERSION_TAG=${VERSION_TAG}
      - DATABASE_URL=${DATABASE_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # Config path
      - CONFIG_PATH=/app/config.yaml
    depends_on:
      - db

  db:
    image: postgres:17.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
