name: Life Log GitHub Actions
run-name: ${{ github.actor }} 🚀
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  env:
    GO_VERSION: 1.24.0
    GOLANGCI_LINT_VERSION: v2.0.2

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v7.0.0
        with:
          version: ${{env.GOLANGCI_LINT_VERSION}}
          args: --timeout=5m

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Test
        run: |
          go test -race ./...

  build:
    strategy:
      matrix:
        go-version: [^1.24]
        os: [ubuntu-latest]
    needs: [lint, test]
    runs-on: ${{matrix.os}}
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{matrix.go-version}}
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Build
        run: |
          go build ./cmd/life-log

